name: Release PR

permissions:
  pull-requests: write
  contents: write

on:
  workflow_dispatch:

jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - uses: cargo-bins/cargo-binstall@main
      - name: Install release-plz
        run: cargo binstall -y release-plz
      - name: Create or update release PR
        run: release-plz release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
